# Generated by Django 2.2.6 on 2020-07-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMSDevice',
            fields=[
                ('device_id', models.CharField(default=0, max_length=30, primary_key=True, serialize=False, verbose_name='设备序列号')),
                ('device_name', models.CharField(default='', max_length=30, null=True, verbose_name='设备名称')),
                ('device_passwd', models.CharField(default='', max_length=30, verbose_name='设备密码')),
                ('device_mac', models.CharField(default='', max_length=30, null=True, verbose_name='设备mac地址')),
                ('device_location', models.CharField(default='0,0', max_length=30, null=True, verbose_name='设备地址')),
                ('is_active', models.BooleanField(default=False, null=True, verbose_name='是否激活')),
                ('pm25_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='PM25阈值')),
                ('pm10_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='PM10阈值')),
                ('so2_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='SO2阈值')),
                ('no2_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='NO2阈值')),
                ('co_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='CO阈值')),
                ('o3_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='O3阈值')),
                ('do_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='DO阈值')),
                ('cod_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='COD阈值')),
                ('bod_t', models.FloatField(default=0, max_length=30, null=True, verbose_name='BOD阈值')),
                ('freq', models.FloatField(default=0, null=True, verbose_name='信号频率')),
                ('update_status', models.BooleanField(default=0, null=True, verbose_name='设备同步状态')),
                ('update_time', models.CharField(default='', max_length=30, null=True, verbose_name='更新时间')),
                ('device_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='设备同步时间')),
                ('last_login_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='设备最后上线时间')),
                ('last_logout_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='设备最后下线时间')),
            ],
        ),
        migrations.CreateModel(
            name='EMSDeviceConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25_t', models.FloatField(default=0, max_length=30, verbose_name='PM25阈值')),
                ('pm10_t', models.FloatField(default=0, max_length=30, verbose_name='PM10阈值')),
                ('so2_t', models.FloatField(default=0, max_length=30, verbose_name='SO2阈值')),
                ('no2_t', models.FloatField(default=0, max_length=30, verbose_name='NO2阈值')),
                ('co_t', models.FloatField(default=0, max_length=30, verbose_name='CO阈值')),
                ('o3_t', models.FloatField(default=0, max_length=30, verbose_name='O3阈值')),
                ('do_t', models.FloatField(default=0, max_length=30, verbose_name='DO阈值')),
                ('cod_t', models.FloatField(default=0, max_length=30, verbose_name='COD阈值')),
                ('bod_t', models.FloatField(default=0, max_length=30, verbose_name='BOD阈值')),
                ('freq', models.FloatField(default=0, verbose_name='信号频率')),
                ('update_status', models.BooleanField(default=0, verbose_name='设备同步状态')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('device_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='设备同步时间')),
                ('Device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='EMSDevice.EMSDevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5浓度')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10浓度')),
                ('so2', models.FloatField(default=0, verbose_name='SO2浓度')),
                ('no2', models.FloatField(default=0, verbose_name='NO2浓度')),
                ('co', models.FloatField(default=0, verbose_name='CO浓度')),
                ('o3', models.FloatField(default=0, verbose_name='O3浓度')),
                ('air_temp', models.FloatField(default=0, verbose_name='空气温度')),
                ('humidity', models.FloatField(default=0, verbose_name='空气湿度')),
                ('wind_dir', models.CharField(default='', max_length=4, verbose_name='风向')),
                ('wind_speed', models.FloatField(default=0, verbose_name='风速')),
                ('pressure', models.FloatField(default=0, verbose_name='大气压')),
                ('water_temp', models.FloatField(default=0, verbose_name='水体温度')),
                ('ph', models.FloatField(default=0, verbose_name='水体PH')),
                ('do', models.FloatField(default=0, verbose_name='水体DO')),
                ('cod', models.FloatField(default=0, verbose_name='水体COD')),
                ('bod', models.FloatField(default=0, verbose_name='水体BOD')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EMSDevice.EMSDevice')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5浓度')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10浓度')),
                ('so2', models.FloatField(default=0, verbose_name='SO2浓度')),
                ('no2', models.FloatField(default=0, verbose_name='NO2浓度')),
                ('co', models.FloatField(default=0, verbose_name='CO浓度')),
                ('o3', models.FloatField(default=0, verbose_name='O3浓度')),
                ('air_temp', models.FloatField(default=0, verbose_name='空气温度')),
                ('humidity', models.FloatField(default=0, verbose_name='空气湿度')),
                ('wind_dir', models.CharField(default='', max_length=4, verbose_name='风向')),
                ('wind_speed', models.FloatField(default=0, verbose_name='风速')),
                ('pressure', models.FloatField(default=0, verbose_name='大气压')),
                ('water_temp', models.FloatField(default=0, verbose_name='水体温度')),
                ('ph', models.FloatField(default=0, verbose_name='水体PH')),
                ('do', models.FloatField(default=0, verbose_name='水体DO')),
                ('cod', models.FloatField(default=0, verbose_name='水体COD')),
                ('bod', models.FloatField(default=0, verbose_name='水体BOD')),
                ('time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='EMSDevice.EMSDevice')),
            ],
        ),
    ]
