# Generated by Django 2.2.6 on 2020-07-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EMSDevice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSAlarmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlarmAt', models.DateTimeField(auto_now_add=True, verbose_name='报警时间')),
                ('AlarmValue', models.FloatField(default=0, verbose_name='报警值')),
                ('AlarmType', models.CharField(default='', max_length=20, verbose_name='报警类型')),
                ('Status', models.BooleanField(default=False, verbose_name='处理状态')),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='报警信息表', to='EMSDevice.EMSDevice')),
            ],
        ),
        migrations.CreateModel(
            name='EMSAlarmHandle',
            fields=[
                ('AlarmHandle_ID', models.IntegerField(primary_key=True, serialize=False, verbose_name='报警处理信息表')),
                ('Person_in_Charger', models.CharField(default='', max_length=10, verbose_name='负责人员')),
                ('Phone', models.CharField(default='', max_length=12, verbose_name='处理人员电话')),
                ('handle_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('handle_describle', models.CharField(default='', max_length=100, verbose_name='处理说明')),
                ('AlarmInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='处理信息表', to='EMSAlarm.EMSAlarmInfo')),
            ],
        ),
    ]
